#!/usr/bin/env python3
"""
Katalog materi Kaigo — SINGLE SOURCE OF TRUTH.

Semua metadata modul Kaigo tinggal di sini. scripts/build_kaigo_page.py membaca
file ini untuk membangun Materi/Kaigo.html; scripts/validate.py memakainya untuk
memastikan katalog dan file di disk tetap sinkron.

Metadata TIDAK ditebak dari judul — diturunkan dari isi tiap modul:
  - level      : posisi dalam kurikulum (fondasi → praktik → lanjutan),
                 bukan dari kata "dasar"/"lanjut" di judul
  - duration   : estimasi menit = (jumlah kata / 200 wpm) + 1 menit per soal kuis
  - order      : urutan belajar dalam kategorinya
  - prerequisite / recommended_next : rute belajar berurutan
  - title_ja   : diambil dari <h1> modul; None bila modul memang tidak punya
                 judul Jepang sendiri (tidak dikarang)

Menambah modul Kaigo baru:
  1. Buat Materi/Kaigo-Nama.html
  2. Tambahkan entri di MODULES (bawah)
  3. python3 scripts/build_kaigo_page.py
  4. python3 scripts/validate.py
"""

# ── Kategori: (key, nama tampil, ikon, deskripsi) ────────────────────────────
CATEGORIES = [
    ('dasar',     'Dasar Kaigo',                  '🏠',
     'Fondasi profesi: jalur karier, martabat manusia, kemandirian, dan prinsip dasar perawatan.'),
    ('bahasa',    'Bahasa & Komunikasi',          '💬',
     'Bahasa Jepang untuk Kaigo, keigo, percakapan, dan teknik komunikasi dengan lansia.'),
    ('praktik',   'Praktik Perawatan',            '🤲',
     'Prosedur harian: mandi, makan, toilet, transfer, ganti pakaian, dan perawatan malam.'),
    ('kesehatan', 'Kesehatan & Medis',            '🏥',
     'Penyakit lansia, fisiologi tubuh, prosedur medis, dan penanganan darurat.'),
    ('dokumen',   'Dokumentasi',                  '📝',
     'Penulisan rekod asuhan, laporan, dan proses perawatan (kaigo katei).'),
    ('hukum',     'Hukum, Etika & Sistem Sosial', '⚖️',
     'Asuransi perawatan, jaminan sosial, hak asasi, etika profesi, dan perlindungan lansia.'),
    ('ujian',     'Persiapan Ujian',              '🎓',
     'Latihan soal ujian nasional 介護福祉士 dan kuis per level.'),
]

# ── Level: (key, label, urutan) ──────────────────────────────────────────────
LEVELS = [
    ('pemula',   'Pemula',   1),
    ('menengah', 'Menengah', 2),
    ('mahir',    'Mahir',    3),
]

# ── Modul ───────────────────────────────────────────────────────────────────
MODULES = {

    # ── dasar ──
    'Kaigo-Fukushishi-Overview': {
        "filename": 'Kaigo-Fukushishi-Overview.html',
        "category": 'dasar',
        "title": 'Jalur, Ujian, Roadmap',
        "title_ja": None,
        "description": 'Panduan lengkap 介護福祉士 untuk WNI: jalur EPA/SSW/magang, syarat bahasa, roadmap belajar dari N4 ke lisensi nasional.',
        "level": 'pemula',
        "order": 1,
        "duration": 16,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'ujian', 'n4'],
        "recommended_next": 'Kaigo-Ningen-Songen',
        "icon": '🏠',
    },
    'Kaigo-Ningen-Songen': {
        "filename": 'Kaigo-Ningen-Songen.html',
        "category": 'dasar',
        "title": 'Martabat Manusia & Kemandirian',
        "title_ja": '人間の尊厳と自立',
        "description": 'Panduan profesional 人間の尊厳と自立 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'pemula',
        "order": 2,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'ujian'],
        "recommended_next": 'Kaigo-Jiritsu-Shien',
        "icon": '🕊️',
    },
    'Kaigo-Jiritsu-Shien': {
        "filename": 'Kaigo-Jiritsu-Shien.html',
        "category": 'dasar',
        "title": '自立支援介護 じりつしえんかいご',
        "title_ja": '自立支援介護',
        "description": 'Dukungan kemandirian lansia 自立支援. Filosofi jiritsu shien, 4 pendekatan praktis, metode pelaksanaan, dan etika mendampingi lansia mandiri di Jepang.',
        "level": 'pemula',
        "order": 3,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'lansia'],
        "recommended_next": 'Kaigo-Baisutikku',
        "icon": '🦯',
    },
    'Kaigo-Baisutikku': {
        "filename": 'Kaigo-Baisutikku.html',
        "category": 'dasar',
        "title": '7 Prinsip Biestek dalam Komunikasi Kaigo',
        "title_ja": 'バイスティックの',
        "description": 'Panduan lengkap バイスティックの7原則 dalam kaigo untuk ujian介護福祉士: teori, prosedur, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'pemula',
        "order": 4,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'ujian'],
        "recommended_next": 'Kaigo-Bunka',
        "icon": '🤝',
    },
    'Kaigo-Bunka': {
        "filename": 'Kaigo-Bunka.html',
        "category": 'dasar',
        "title": '介護の文化と倫理 介護文化・職業倫理',
        "title_ja": '介護の文化と倫理',
        "description": 'Budaya kaigo Jepang 日本の介護文化. Pelajari etika profesi, kerja tim, pengembangan diri, dan norma budaya kerja di fasilitas perawatan lansia Jepang.',
        "level": 'pemula',
        "order": 5,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'lansia'],
        "recommended_next": 'Kaigo-ICF-Assessment',
        "icon": '🎎',
    },
    'Kaigo-ICF-Assessment': {
        "filename": 'Kaigo-ICF-Assessment.html',
        "category": 'dasar',
        "title": 'ICF & アセスメント完全ガイド ICF・介護過程',
        "title_ja": 'アセスメント完全ガイド',
        "description": 'ICF分類 · 介護過程4段階 · アセスメントシート · ケアプラン — Nihonggo Pro Academy',
        "level": 'menengah',
        "order": 6,
        "duration": 10,
        "prerequisite": 'Kaigo-Bunka',
        "tags": ['dasar', 'fondasi'],
        "recommended_next": 'Kaigo-Fukushiyo-Gu',
        "icon": '📋',
    },
    'Kaigo-Fukushiyo-Gu': {
        "filename": 'Kaigo-Fukushiyo-Gu.html',
        "category": 'dasar',
        "title": 'Alat Bantu Perawatan Lansia',
        "title_ja": '福祉用具',
        "description": 'Panduan lengkap福祉用具 (alat bantu perawatan) dalam kaigo: jenis alat, cara pakai, kosakata bahasa Jepang, dialog dengan residen, dan quiz persiapan ujian kaigo.',
        "level": 'menengah',
        "order": 7,
        "duration": 10,
        "prerequisite": 'Kaigo-ICF-Assessment',
        "tags": ['dasar', 'fondasi', 'lansia', 'ujian'],
        "recommended_next": 'Kaigo-Chiiki-Shakai',
        "icon": '🦽',
    },
    'Kaigo-Chiiki-Shakai': {
        "filename": 'Kaigo-Chiiki-Shakai.html',
        "category": 'dasar',
        "title": 'Masyarakat Inklusif Berbasis Komunitas',
        "title_ja": '地域共生社会',
        "description": 'Panduan profesional 地域共生社会 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'pemula',
        "order": 8,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'ujian'],
        "recommended_next": 'Kaigo-Homecare',
        "icon": '🏘️',
    },
    'Kaigo-Homecare': {
        "filename": 'Kaigo-Homecare.html',
        "category": 'dasar',
        "title": '訪問介護完全ガイド 在宅ケア',
        "title_ja": '訪問介護完全ガイド',
        "description": 'Perawatan di rumah ホームヘルパー. Jenis layanan, teknik perawatan khusus di lingkungan rumah, dan cara mendukung keluarga lansia untuk tenaga homecare Jepang.',
        "level": 'pemula',
        "order": 9,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dasar', 'fondasi', 'lansia'],
        "recommended_next": None,
        "icon": '🏡',
    },

    # ── bahasa ──
    'Kaigo-N5': {
        "filename": 'Kaigo-N5.html',
        "category": 'bahasa',
        "title": 'Kaigo N5',
        "title_ja": '介護日本語',
        "description": 'Kosakata kaigo dasar level N5 — bagian tubuh, kegiatan sehari-hari, angka, waktu, dan ekspresi dasar untuk pekerja kaigo pemula.',
        "level": 'pemula',
        "order": 1,
        "duration": 13,
        "prerequisite": None,
        "tags": ['bahasa', 'komunikasi', 'n5'],
        "recommended_next": 'Kaigo-Bahasa',
        "icon": '🔤',
    },
    'Kaigo-Bahasa': {
        "filename": 'Kaigo-Bahasa.html',
        "category": 'bahasa',
        "title": 'Kosakata, Dialog, Keigo',
        "title_ja": '日本語',
        "description": '500+ kosakata kaigo: bagian tubuh, kondisi, peralatan, tindakan. Dialog situasional nyata (makan/mandi/darurat) dan keigo untuk perawat lansia.',
        "level": 'pemula',
        "order": 2,
        "duration": 21,
        "prerequisite": None,
        "tags": ['bahasa', 'komunikasi', 'keigo', 'lansia', 'darurat'],
        "recommended_next": 'Kaigo-Nihongo-N4',
        "icon": '💬',
    },
    'Kaigo-Nihongo-N4': {
        "filename": 'Kaigo-Nihongo-N4.html',
        "category": 'bahasa',
        "title": 'Bahasa Jepang Kaigo N4',
        "title_ja": None,
        "description": 'Bahasa Jepang kaigo level N4 untuk 介護福祉士: kosakata, pola kalimat, dan dialog sehari-hari dalam situasi perawatan lansia.',
        "level": 'menengah',
        "order": 3,
        "duration": 12,
        "prerequisite": 'Kaigo-Bahasa',
        "tags": ['bahasa', 'komunikasi', 'lansia', 'n4'],
        "recommended_next": 'Kaigo-Kosakata-Klinik',
        "icon": '📗',
    },
    'Kaigo-Kosakata-Klinik': {
        "filename": 'Kaigo-Kosakata-Klinik.html',
        "category": 'bahasa',
        "title": '介護福祉士',
        "title_ja": None,
        "description": 'Kosakata medis dan klinis lengkap untuk 介護福祉士 — penyakit, obat-obatan, istilah prosedur medis, dan bahasa laporan yang sering muncul di ujian nasional 国家試験.',
        "level": 'menengah',
        "order": 4,
        "duration": 17,
        "prerequisite": 'Kaigo-Nihongo-N4',
        "tags": ['bahasa', 'komunikasi', 'ujian'],
        "recommended_next": 'Kaigo-Komunikasi',
        "icon": '🩺',
    },
    'Kaigo-Komunikasi': {
        "filename": 'Kaigo-Komunikasi.html',
        "category": 'bahasa',
        "title": 'Komunikasi & Psikologi Perawatan',
        "title_ja": None,
        "description": 'Komunikasi dan psikologi perawatan 介護福祉士: teknik komunikasi efektif dengan lansia, keluarga, dan tim medis dalam bahasa Jepang.',
        "level": 'pemula',
        "order": 5,
        "duration": 11,
        "prerequisite": None,
        "tags": ['bahasa', 'komunikasi', 'lansia'],
        "recommended_next": 'Kaigo-Kaiwa-Technique',
        "icon": '🧠',
    },
    'Kaigo-Kaiwa-Technique': {
        "filename": 'Kaigo-Kaiwa-Technique.html',
        "category": 'bahasa',
        "title": 'Teknik Komunikasi dalam Kaigo',
        "title_ja": '介護コミュニケーション技術',
        "description": 'Panduan profesional 介護コミュニケーション技術 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'pemula',
        "order": 6,
        "duration": 10,
        "prerequisite": None,
        "tags": ['bahasa', 'komunikasi', 'ujian'],
        "recommended_next": 'Kaigo-Higeongo-Comm',
        "icon": '💭',
    },
    'Kaigo-Higeongo-Comm': {
        "filename": 'Kaigo-Higeongo-Comm.html',
        "category": 'bahasa',
        "title": 'Komunikasi Non-Verbal dalam Kaigo',
        "title_ja": '非言語コミュニケーション',
        "description": 'Panduan lengkap 非言語コミュニケーション dalam kaigo untuk ujian介護福祉士: teori, contoh, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'menengah',
        "order": 7,
        "duration": 10,
        "prerequisite": 'Kaigo-Kaiwa-Technique',
        "tags": ['bahasa', 'komunikasi', 'ujian'],
        "recommended_next": 'Kaigo-Speaking',
        "icon": '🤲',
    },
    'Kaigo-Speaking': {
        "filename": 'Kaigo-Speaking.html',
        "category": 'bahasa',
        "title": 'Kaigo Speaking 介護スピーキング',
        "title_ja": '介護スピーキング',
        "description": 'Latihan percakapan bahasa Jepang untuk kaigo — dialog nyata dengan residen, keluarga, dan tim medis. Dilengkapi audio TTS dan latihan roleplay.',
        "level": 'menengah',
        "order": 8,
        "duration": 15,
        "prerequisite": 'Kaigo-Higeongo-Comm',
        "tags": ['bahasa', 'komunikasi'],
        "recommended_next": 'Kaigo-Kazoku-Shien',
        "icon": '🗣️',
    },
    'Kaigo-Kazoku-Shien': {
        "filename": 'Kaigo-Kazoku-Shien.html',
        "category": 'bahasa',
        "title": 'Dukungan Keluarga & Komunikasi',
        "title_ja": '家族支援とコミュニケーション',
        "description": 'Panduan profesional 家族支援とコミュニケーション dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 9,
        "duration": 10,
        "prerequisite": 'Kaigo-Speaking',
        "tags": ['bahasa', 'komunikasi', 'ujian'],
        "recommended_next": 'Kaigo-Taju-Renkei',
        "icon": '👪',
    },
    'Kaigo-Taju-Renkei': {
        "filename": 'Kaigo-Taju-Renkei.html',
        "category": 'bahasa',
        "title": 'Kolaborasi Multidisiplin',
        "title_ja": '多職種連携とチームアプローチ',
        "description": 'Panduan profesional 多職種連携とチームアプローチ dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 10,
        "duration": 10,
        "prerequisite": 'Kaigo-Kazoku-Shien',
        "tags": ['bahasa', 'komunikasi', 'ujian'],
        "recommended_next": 'Kaigo-Dementia-Communication',
        "icon": '🤝',
    },
    'Kaigo-Dementia-Communication': {
        "filename": 'Kaigo-Dementia-Communication.html',
        "category": 'bahasa',
        "title": 'Kaigo Dementia Communication 認知症コミュニケーション',
        "title_ja": '認知症コミュニケーション',
        "description": 'Teknik komunikasi efektif dengan residen demensia — validasi, dialog nyata, dan frasa kunci kaigo.',
        "level": 'menengah',
        "order": 11,
        "duration": 10,
        "prerequisite": 'Kaigo-Taju-Renkei',
        "tags": ['bahasa', 'komunikasi', 'demensia'],
        "recommended_next": 'Kaigo-Speaking-Lanjut',
        "icon": '🧩',
    },
    'Kaigo-Speaking-Lanjut': {
        "filename": 'Kaigo-Speaking-Lanjut.html',
        "category": 'bahasa',
        "title": 'Speaking Kaigo Lanjutan 介護会話応用',
        "title_ja": '介護会話応用',
        "description": 'Speaking kaigo lanjutan 介護会話応用. Percakapan perawatan lansia tingkat lanjut untuk tenaga kerja kaigo di Jepang.',
        "level": 'mahir',
        "order": 12,
        "duration": 10,
        "prerequisite": 'Kaigo-Dementia-Communication',
        "tags": ['bahasa', 'komunikasi', 'lansia'],
        "recommended_next": 'Kaigo-Speaking-Advanced',
        "icon": '🗣️',
    },
    'Kaigo-Speaking-Advanced': {
        "filename": 'Kaigo-Speaking-Advanced.html',
        "category": 'bahasa',
        "title": 'Kaigo Speaking Advanced 介護会話応用',
        "title_ja": '介護会話応用レベル',
        "description": 'Speaking kaigo lanjutan — koordinasi multi-profesi, laporan keluarga, frasa profesional N2-N1.',
        "level": 'mahir',
        "order": 13,
        "duration": 10,
        "prerequisite": 'Kaigo-Speaking-Lanjut',
        "tags": ['bahasa', 'komunikasi', 'n2'],
        "recommended_next": 'Kaigo-Speaking-N2',
        "icon": '🎙️',
    },
    'Kaigo-Speaking-N2': {
        "filename": 'Kaigo-Speaking-N2.html',
        "category": 'bahasa',
        "title": 'Kaigo Speaking N2 介護会話N2',
        "title_ja": '介護会話',
        "description": 'Speaking kaigo level N2 — dialog pelaporan, komunikasi keluarga, frasa profesional.',
        "level": 'mahir',
        "order": 14,
        "duration": 10,
        "prerequisite": 'Kaigo-Speaking-Advanced',
        "tags": ['bahasa', 'komunikasi', 'n2'],
        "recommended_next": None,
        "icon": '🎧',
    },

    # ── praktik ──
    'Kaigo-ADL-Guide': {
        "filename": 'Kaigo-ADL-Guide.html',
        "category": 'praktik',
        "title": 'Panduan ADL Lengkap 日常生活動作完全ガイド',
        "title_ja": '日常生活動作完全ガイド',
        "description": 'Makan · Mandi · Toileting · Berpakaian · Berpindah — teknik & vocabulary — Nihonggo Pro Academy',
        "level": 'pemula',
        "order": 1,
        "duration": 10,
        "prerequisite": None,
        "tags": ['praktik', 'perawatan'],
        "recommended_next": 'Kaigo-Iijo-Ido',
        "icon": '📅',
    },
    'Kaigo-Iijo-Ido': {
        "filename": 'Kaigo-Iijo-Ido.html',
        "category": 'praktik',
        "title": 'Bantuan Transfer & Mobilitas Kaigo',
        "title_ja": '移乗・移動介助',
        "description": 'Panduan lengkap 移乗・移動介助 dalam kaigo untuk ujian介護福祉士: teori, prosedur, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'menengah',
        "order": 2,
        "duration": 10,
        "prerequisite": 'Kaigo-ADL-Guide',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Koi-Kaijo',
        "icon": '🦽',
    },
    'Kaigo-Koi-Kaijo': {
        "filename": 'Kaigo-Koi-Kaijo.html',
        "category": 'praktik',
        "title": 'Bantuan Ganti Pakaian',
        "title_ja": '更衣介助',
        "description": 'Panduan profesional 更衣介助 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 3,
        "duration": 10,
        "prerequisite": 'Kaigo-Iijo-Ido',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Shokuji-Guide',
        "icon": '👕',
    },
    'Kaigo-Shokuji-Guide': {
        "filename": 'Kaigo-Shokuji-Guide.html',
        "category": 'praktik',
        "title": 'Bantuan Makan & Perawatan Menelan',
        "title_ja": '食事介助と嚥下ケア',
        "description": 'Panduan profesional 食事介助と嚥下ケア dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 4,
        "duration": 10,
        "prerequisite": 'Kaigo-Koi-Kaijo',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Nyuyoku-Care',
        "icon": '🍚',
    },
    'Kaigo-Nyuyoku-Care': {
        "filename": 'Kaigo-Nyuyoku-Care.html',
        "category": 'praktik',
        "title": 'Bantuan Mandi Lansia',
        "title_ja": '入浴介護',
        "description": 'Panduan lengkap入浴介護 (bantuan mandi) dalam kaigo: prosedur全身浴・シャワー浴・清拭, checklist keamanan, observasi kondisi kulit, dialog bahasa Jepang, dan quiz ujian Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 5,
        "duration": 10,
        "prerequisite": 'Kaigo-Shokuji-Guide',
        "tags": ['praktik', 'perawatan', 'lansia', 'ujian'],
        "recommended_next": 'Kaigo-Haisetsu-Care',
        "icon": '🛁',
    },
    'Kaigo-Haisetsu-Care': {
        "filename": 'Kaigo-Haisetsu-Care.html',
        "category": 'praktik',
        "title": 'Bantuan Toilet & Higiene',
        "title_ja": '排泄介護',
        "description": 'Panduan lengkap排泄介護 (bantuan toilet) dalam kaigo: prosedur トイレ、ポータブルトイレ、おむつ交換, dialog sopan, observasi ekskreta, dan quiz ujian Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 6,
        "duration": 10,
        "prerequisite": 'Kaigo-Nyuyoku-Care',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Kuchiku-Care',
        "icon": '🚻',
    },
    'Kaigo-Kuchiku-Care': {
        "filename": 'Kaigo-Kuchiku-Care.html',
        "category": 'praktik',
        "title": 'Perawatan Mulut Lansia',
        "title_ja": '口腔ケア',
        "description": 'Panduan lengkap口腔ケア (oral care) dalam kaigo: prosedur sikat gigi, gigi palsu, mencegah誤嚥性肺炎, kosakata Jepang, dan dialog nyata dengan residen.',
        "level": 'menengah',
        "order": 7,
        "duration": 10,
        "prerequisite": 'Kaigo-Haisetsu-Care',
        "tags": ['praktik', 'perawatan', 'lansia'],
        "recommended_next": 'Kaigo-Taino-Kanri',
        "icon": '🦷',
    },
    'Kaigo-Taino-Kanri': {
        "filename": 'Kaigo-Taino-Kanri.html',
        "category": 'praktik',
        "title": 'Manajemen Posisi & Pencegahan Luka Tekan',
        "title_ja": '体位管理と褥瘡予防',
        "description": 'Panduan profesional 体位管理と褥瘡予防 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 8,
        "duration": 10,
        "prerequisite": 'Kaigo-Kuchiku-Care',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Kyoshuku-Yobo',
        "icon": '🛏️',
    },
    'Kaigo-Kyoshuku-Yobo': {
        "filename": 'Kaigo-Kyoshuku-Yobo.html',
        "category": 'praktik',
        "title": 'Pencegahan Kontraktur Kaigo',
        "title_ja": '拘縮予防',
        "description": 'Panduan lengkap 拘縮予防 dalam kaigo: teori, prosedur, dialog Jepang, kosakata, dan quiz persiapan ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 9,
        "duration": 10,
        "prerequisite": 'Kaigo-Taino-Kanri',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Juukankyo-Seibi',
        "icon": '🤸',
    },
    'Kaigo-Juukankyo-Seibi': {
        "filename": 'Kaigo-Juukankyo-Seibi.html',
        "category": 'praktik',
        "title": 'Penataan Lingkungan Rumah yang Aman Kaigo',
        "title_ja": '住環境整備',
        "description": 'Panduan lengkap 住環境整備 dalam kaigo untuk ujian介護福祉士: teori, prosedur, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'menengah',
        "order": 10,
        "duration": 10,
        "prerequisite": 'Kaigo-Kyoshuku-Yobo',
        "tags": ['praktik', 'perawatan', 'ujian'],
        "recommended_next": 'Kaigo-Yakan-Care',
        "icon": '🏗️',
    },
    'Kaigo-Yakan-Care': {
        "filename": 'Kaigo-Yakan-Care.html',
        "category": 'praktik',
        "title": 'Perawatan Malam',
        "title_ja": '夜間ケア・夜勤',
        "description": 'Panduan lengkap夜間ケア dan夜勤 dalam kaigo: prosedur keamanan malam, pengecekan berkala, penanganan insiden, kosakata, dan dialog bahasa Jepang untuk shift malam.',
        "level": 'menengah',
        "order": 11,
        "duration": 10,
        "prerequisite": 'Kaigo-Juukankyo-Seibi',
        "tags": ['praktik', 'perawatan'],
        "recommended_next": 'Kaigo-Safety-Guide',
        "icon": '🌙',
    },
    'Kaigo-Safety-Guide': {
        "filename": 'Kaigo-Safety-Guide.html',
        "category": 'praktik',
        "title": 'Panduan Keselamatan Kaigo 介護安全管理',
        "title_ja": '介護安全管理',
        "description": 'Panduan Keselamatan Kaigo 介護安全管理 — Nihonggo Pro Academy',
        "level": 'pemula',
        "order": 12,
        "duration": 10,
        "prerequisite": None,
        "tags": ['praktik', 'perawatan'],
        "recommended_next": 'Kaigo-Prosedur',
        "icon": '🦺',
    },
    'Kaigo-Prosedur': {
        "filename": 'Kaigo-Prosedur.html',
        "category": 'praktik',
        "title": 'Prosedur Perawatan Standar',
        "title_ja": '手順書',
        "description": 'Prosedur perawatan kaigo 介護手順. Panduan SOP standar Jepang untuk memandikan, mobilisasi, makan, dan prosedur perawatan sehari-hari di fasilitas kaigo.',
        "level": 'menengah',
        "order": 13,
        "duration": 17,
        "prerequisite": 'Kaigo-Safety-Guide',
        "tags": ['praktik', 'perawatan'],
        "recommended_next": 'Kaigo-Rehabilitasi',
        "icon": '📖',
    },
    'Kaigo-Rehabilitasi': {
        "filename": 'Kaigo-Rehabilitasi.html',
        "category": 'praktik',
        "title": 'Rehabilitasi Kaigo リハビリ',
        "title_ja": 'リハビリ',
        "description": 'ADL, ROM, 廃用症候群, PT/OT/ST kolaborasi dalam rehabilitasi kaigo.',
        "level": 'menengah',
        "order": 14,
        "duration": 10,
        "prerequisite": 'Kaigo-Prosedur',
        "tags": ['praktik', 'perawatan'],
        "recommended_next": 'Kaigo-Prosedur-Lanjut',
        "icon": '🏃',
    },
    'Kaigo-Prosedur-Lanjut': {
        "filename": 'Kaigo-Prosedur-Lanjut.html',
        "category": 'praktik',
        "title": 'Prosedur Kaigo Lanjutan 介護手順応用',
        "title_ja": '介護手順応用',
        "description": 'Prosedur Kaigo Lanjutan 介護手順応用 — Nihonggo Pro Academy',
        "level": 'mahir',
        "order": 15,
        "duration": 10,
        "prerequisite": 'Kaigo-Rehabilitasi',
        "tags": ['praktik', 'perawatan'],
        "recommended_next": 'Kaigo-Terminal-Care',
        "icon": '📚',
    },
    'Kaigo-Terminal-Care': {
        "filename": 'Kaigo-Terminal-Care.html',
        "category": 'praktik',
        "title": 'Terminal Care & Paliatif 終末期ケア',
        "title_ja": '終末期ケア',
        "description": 'Terminal Care & Paliatif 終末期ケア — Nihonggo Pro Academy',
        "level": 'mahir',
        "order": 16,
        "duration": 10,
        "prerequisite": 'Kaigo-Prosedur-Lanjut',
        "tags": ['praktik', 'perawatan'],
        "recommended_next": None,
        "icon": '🕯️',
    },

    # ── kesehatan ──
    'Kaigo-Roka-Shikumi': {
        "filename": 'Kaigo-Roka-Shikumi.html',
        "category": 'kesehatan',
        "title": 'Fisiologi Penuaan Kaigo',
        "title_ja": '老化のしくみ',
        "description": 'Panduan lengkap 老化のしくみ dalam kaigo: teori, prosedur, dialog Jepang, kosakata, dan quiz persiapan ujian nasional Kaigo Fukushishi.',
        "level": 'pemula',
        "order": 1,
        "duration": 10,
        "prerequisite": None,
        "tags": ['kesehatan', 'medis', 'ujian'],
        "recommended_next": 'Kaigo-Kokyu-Junkan',
        "icon": '🧓',
    },
    'Kaigo-Kokyu-Junkan': {
        "filename": 'Kaigo-Kokyu-Junkan.html',
        "category": 'kesehatan',
        "title": 'Fisiologi Pernapasan & Sirkulasi dalam Kaigo',
        "title_ja": '呼吸・循環のしくみと介護',
        "description": 'Panduan profesional 呼吸・循環のしくみと介護 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 2,
        "duration": 10,
        "prerequisite": 'Kaigo-Roka-Shikumi',
        "tags": ['kesehatan', 'medis', 'ujian'],
        "recommended_next": 'Kaigo-Shouka-Haisetsu',
        "icon": '🫁',
    },
    'Kaigo-Shouka-Haisetsu': {
        "filename": 'Kaigo-Shouka-Haisetsu.html',
        "category": 'kesehatan',
        "title": 'Fisiologi Pencernaan & Ekskresi',
        "title_ja": '消化・排泄のしくみと介護',
        "description": 'Panduan profesional 消化・排泄のしくみと介護 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 3,
        "duration": 10,
        "prerequisite": 'Kaigo-Kokyu-Junkan',
        "tags": ['kesehatan', 'medis', 'ujian'],
        "recommended_next": 'Kaigo-Ninchi-Kino',
        "icon": '🍽️',
    },
    'Kaigo-Ninchi-Kino': {
        "filename": 'Kaigo-Ninchi-Kino.html',
        "category": 'kesehatan',
        "title": 'Fungsi Kognitif & Gangguan Fungsi Otak Tinggi',
        "title_ja": '認知機能と高次脳機能障害',
        "description": 'Panduan profesional 認知機能と高次脳機能障害 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 4,
        "duration": 10,
        "prerequisite": 'Kaigo-Shouka-Haisetsu',
        "tags": ['kesehatan', 'medis', 'ujian'],
        "recommended_next": 'Kaigo-Penyakit',
        "icon": '💡',
    },
    'Kaigo-Penyakit': {
        "filename": 'Kaigo-Penyakit.html',
        "category": 'kesehatan',
        "title": 'Penyakit Utama Lansia & Pendekatan Kaigo',
        "title_ja": None,
        "description": 'Penyakit umum lansia dalam kaigo. Panduan memahami demensia, stroke, osteoporosis, dan penyakit kronis lain yang umum ditemui tenaga kaigo di Jepang.',
        "level": 'menengah',
        "order": 5,
        "duration": 13,
        "prerequisite": 'Kaigo-Ninchi-Kino',
        "tags": ['kesehatan', 'medis', 'demensia', 'lansia'],
        "recommended_next": 'Kaigo-Demensia',
        "icon": '🏥',
    },
    'Kaigo-Demensia': {
        "filename": 'Kaigo-Demensia.html',
        "category": 'kesehatan',
        "title": 'Kaigo Demensia 認知症ケア',
        "title_ja": '認知症ケア',
        "description": 'Panduan perawatan demensia (認知症) dalam bahasa Jepang — gejala, komunikasi, BPSD, dan teknik perawatan yang tepat untuk kaigo.',
        "level": 'menengah',
        "order": 6,
        "duration": 15,
        "prerequisite": 'Kaigo-Penyakit',
        "tags": ['kesehatan', 'medis', 'demensia'],
        "recommended_next": 'Kaigo-Alzheimer',
        "icon": '🧩',
    },
    'Kaigo-Alzheimer': {
        "filename": 'Kaigo-Alzheimer.html',
        "category": 'kesehatan',
        "title": 'Alzheimer & Perawatan Khusus アルツハイマー',
        "title_ja": 'アルツハイマー',
        "description": 'Panduan khusus Alzheimer dalam kaigo — stadium, gejala tiap tahap, komunikasi, dan intervensi non-farmakologi.',
        "level": 'menengah',
        "order": 7,
        "duration": 10,
        "prerequisite": 'Kaigo-Demensia',
        "tags": ['kesehatan', 'medis'],
        "recommended_next": 'Kaigo-Parkinson',
        "icon": '🧠',
    },
    'Kaigo-Parkinson': {
        "filename": 'Kaigo-Parkinson.html',
        "category": 'kesehatan',
        "title": 'Perawatan Parkinson パーキンソン病ケア',
        "title_ja": 'パーキンソン病ケア',
        "description": 'Gejala 4 khas · Teknik transfer aman · Komunikasi · Perawatan sehari-hari — Nihonggo Pro Academy',
        "level": 'menengah',
        "order": 8,
        "duration": 10,
        "prerequisite": 'Kaigo-Alzheimer',
        "tags": ['kesehatan', 'medis'],
        "recommended_next": 'Kaigo-Osteoporosis',
        "icon": '🤝',
    },
    'Kaigo-Osteoporosis': {
        "filename": 'Kaigo-Osteoporosis.html',
        "category": 'kesehatan',
        "title": '骨粗鬆症ケア 骨を守るケア',
        "title_ja": '骨粗鬆症ケア',
        "description": 'Osteoporosis pada lansia dalam kaigo 骨粗鬆症. Panduan pencegahan jatuh, penanganan patah tulang, serta dukungan olahraga dan nutrisi untuk tenaga kaigo.',
        "level": 'menengah',
        "order": 9,
        "duration": 10,
        "prerequisite": 'Kaigo-Parkinson',
        "tags": ['kesehatan', 'medis', 'lansia', 'nutrisi'],
        "recommended_next": 'Kaigo-Diabetes-Care',
        "icon": '🦴',
    },
    'Kaigo-Diabetes-Care': {
        "filename": 'Kaigo-Diabetes-Care.html',
        "category": 'kesehatan',
        "title": 'Perawatan Diabetes Kaigo 糖尿病管理',
        "title_ja": '糖尿病管理',
        "description": 'Perawatan diabetes di kaigo 介護. Panduan mengontrol gula darah, menangani hipoglikemia, perawatan kaki, dan manajemen diet untuk lansia diabetik.',
        "level": 'menengah',
        "order": 10,
        "duration": 10,
        "prerequisite": 'Kaigo-Osteoporosis',
        "tags": ['kesehatan', 'medis', 'lansia'],
        "recommended_next": 'Kaigo-Mental-Health',
        "icon": '💉',
    },
    'Kaigo-Mental-Health': {
        "filename": 'Kaigo-Mental-Health.html',
        "category": 'kesehatan',
        "title": 'Mental Health Kaigo 高齢者の精神的健康',
        "title_ja": '高齢者の精神的健康',
        "description": 'Kesehatan mental lansia di kaigo. Penanganan depresi, kecemasan, gangguan tidur, risiko bunuh diri, dan dukungan psikologis untuk tenaga kaigo Jepang.',
        "level": 'menengah',
        "order": 11,
        "duration": 10,
        "prerequisite": 'Kaigo-Diabetes-Care',
        "tags": ['kesehatan', 'medis', 'lansia'],
        "recommended_next": 'Kaigo-Gizi',
        "icon": '💚',
    },
    'Kaigo-Gizi': {
        "filename": 'Kaigo-Gizi.html',
        "category": 'kesehatan',
        "title": 'Gizi & Nutrisi Kaigo 栄養',
        "title_ja": '栄養・食事ケア',
        "description": 'Panduan gizi dan nutrisi dalam kaigo — kosakata nutrisi, jenis diet khusus, masalah menelan, dan perencanaan makan untuk lansia.',
        "level": 'menengah',
        "order": 12,
        "duration": 13,
        "prerequisite": 'Kaigo-Mental-Health',
        "tags": ['kesehatan', 'medis', 'lansia', 'nutrisi'],
        "recommended_next": 'Kaigo-Nutrition',
        "icon": '🥗',
    },
    'Kaigo-Nutrition': {
        "filename": 'Kaigo-Nutrition.html',
        "category": 'kesehatan',
        "title": 'Nutrisi & Gizi Kaigo 栄養管理',
        "title_ja": '栄養管理',
        "description": 'Nutrisi dan gizi kaigo 栄養管理. Panduan kebutuhan gizi lansia, diet khusus penyakit, teknik makan aman, dan pemantauan nutrisi untuk tenaga perawat Jepang.',
        "level": 'menengah',
        "order": 13,
        "duration": 10,
        "prerequisite": 'Kaigo-Gizi',
        "tags": ['kesehatan', 'medis', 'lansia', 'nutrisi'],
        "recommended_next": 'Kaigo-Infection-Control',
        "icon": '🥗',
    },
    'Kaigo-Infection-Control': {
        "filename": 'Kaigo-Infection-Control.html',
        "category": 'kesehatan',
        "title": 'Pengendalian Infeksi Kaigo 感染対策',
        "title_ja": '感染対策',
        "description": 'Pengendalian Infeksi Kaigo 感染対策 — Nihonggo Pro Academy',
        "level": 'menengah',
        "order": 14,
        "duration": 10,
        "prerequisite": 'Kaigo-Nutrition',
        "tags": ['kesehatan', 'medis'],
        "recommended_next": 'Kaigo-Emergency',
        "icon": '🦠',
    },
    'Kaigo-Emergency': {
        "filename": 'Kaigo-Emergency.html',
        "category": 'kesehatan',
        "title": 'Prosedur Darurat Kaigo 緊急時対応完全ガイド',
        "title_ja": '緊急時対応完全ガイド',
        "description": 'CPR · AED · 誤嚥 · 転倒 · 骨折 · 急変時の報告 — Nihonggo Pro Academy',
        "level": 'menengah',
        "order": 15,
        "duration": 10,
        "prerequisite": 'Kaigo-Infection-Control',
        "tags": ['kesehatan', 'medis', 'darurat'],
        "recommended_next": 'Kaigo-Medis-Lanjut',
        "icon": '🚨',
    },
    'Kaigo-Medis-Lanjut': {
        "filename": 'Kaigo-Medis-Lanjut.html',
        "category": 'kesehatan',
        "title": 'Prosedur Medis Kaigo 医療的ケア',
        "title_ja": '医療的ケア',
        "description": 'Vital signs, manajemen obat 6R, perawatan luka, dan tindakan medis yang diizinkan untuk kaigo fukushishi.',
        "level": 'mahir',
        "order": 16,
        "duration": 10,
        "prerequisite": 'Kaigo-Emergency',
        "tags": ['kesehatan', 'medis'],
        "recommended_next": 'Kaigo-Alzheimer-Lanjut',
        "icon": '⚕️',
    },
    'Kaigo-Alzheimer-Lanjut': {
        "filename": 'Kaigo-Alzheimer-Lanjut.html',
        "category": 'kesehatan',
        "title": 'Alzheimer & Demensia Lanjutan 認知症深化',
        "title_ja": '認知症深化',
        "description": 'Alzheimer & Demensia Lanjutan 認知症深化 — Nihonggo Pro Academy',
        "level": 'mahir',
        "order": 17,
        "duration": 10,
        "prerequisite": 'Kaigo-Medis-Lanjut',
        "tags": ['kesehatan', 'medis', 'demensia'],
        "recommended_next": 'Kaigo-Stroke-Lanjut',
        "icon": '🧠',
    },
    'Kaigo-Stroke-Lanjut': {
        "filename": 'Kaigo-Stroke-Lanjut.html',
        "category": 'kesehatan',
        "title": 'Perawatan Pasca Stroke 脳卒中後ケア応用',
        "title_ja": '脳卒中後ケア応用',
        "description": '片麻痺 · 失語 · 嚥下障害 · 高次脳機能障害 · リハビリ支援 — Nihonggo Pro Academy',
        "level": 'mahir',
        "order": 18,
        "duration": 10,
        "prerequisite": 'Kaigo-Alzheimer-Lanjut',
        "tags": ['kesehatan', 'medis'],
        "recommended_next": 'Kaigo-Medis-Advanced',
        "icon": '⚕️',
    },
    'Kaigo-Medis-Advanced': {
        "filename": 'Kaigo-Medis-Advanced.html',
        "category": 'kesehatan',
        "title": 'Kaigo Medis Lanjutan 医療連携応用',
        "title_ja": '医療連携応用',
        "description": 'Kaigo Medis Lanjutan 医療連携応用 — Nihonggo Pro Academy',
        "level": 'mahir',
        "order": 19,
        "duration": 10,
        "prerequisite": 'Kaigo-Stroke-Lanjut',
        "tags": ['kesehatan', 'medis'],
        "recommended_next": 'Kaigo-Katan-Kyuin',
        "icon": '🔬',
    },
    'Kaigo-Katan-Kyuin': {
        "filename": 'Kaigo-Katan-Kyuin.html',
        "category": 'kesehatan',
        "title": 'Suction Dahak Kaigo',
        "title_ja": '喀痰吸引',
        "description": 'Panduan喀痰吸引 (suction dahak) dalam kaigo: prosedur, jenis suction, indikasi, kontraindikasi, kosakata Jepang, dialog, dan quiz ujian Kaigo Fukushishi 医療的ケア.',
        "level": 'mahir',
        "order": 20,
        "duration": 10,
        "prerequisite": 'Kaigo-Medis-Advanced',
        "tags": ['kesehatan', 'medis', 'ujian'],
        "recommended_next": 'Kaigo-Keikan-Eiyo',
        "icon": '🫁',
    },
    'Kaigo-Keikan-Eiyo': {
        "filename": 'Kaigo-Keikan-Eiyo.html',
        "category": 'kesehatan',
        "title": 'Nutrisi Enteral / Tube Feeding',
        "title_ja": '経管栄養',
        "description": 'Panduan profesional 経管栄養 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'mahir',
        "order": 21,
        "duration": 10,
        "prerequisite": 'Kaigo-Katan-Kyuin',
        "tags": ['kesehatan', 'medis', 'nutrisi', 'ujian'],
        "recommended_next": None,
        "icon": '💊',
    },

    # ── dokumen ──
    'Kaigo-Dokumentasi': {
        "filename": 'Kaigo-Dokumentasi.html',
        "category": 'dokumen',
        "title": 'Dokumentasi Kaigo 介護記録',
        "title_ja": '介護記録',
        "description": 'Dokumentasi perawatan kaigo 介護記録. Cara menulis catatan harian perawatan, laporan insiden, dan formulir resmi untuk tenaga kaigo di Jepang.',
        "level": 'pemula',
        "order": 1,
        "duration": 10,
        "prerequisite": None,
        "tags": ['dokumentasi', 'rekod'],
        "recommended_next": 'Kaigo-Rekod',
        "icon": '📝',
    },
    'Kaigo-Rekod': {
        "filename": 'Kaigo-Rekod.html',
        "category": 'dokumen',
        "title": 'Penulisan Rekod & Dokumentasi Asuhan',
        "title_ja": None,
        "description": 'Penulisan rekod dan dokumentasi asuhan 介護福祉士: cara menulis catatan harian, laporan shift, dan dokumentasi resmi dalam bahasa Jepang.',
        "level": 'menengah',
        "order": 2,
        "duration": 10,
        "prerequisite": 'Kaigo-Dokumentasi',
        "tags": ['dokumentasi', 'rekod'],
        "recommended_next": 'Kaigo-Kaigo-Katei',
        "icon": '🗂️',
    },
    'Kaigo-Kaigo-Katei': {
        "filename": 'Kaigo-Kaigo-Katei.html',
        "category": 'dokumen',
        "title": 'Proses Perawatan / Care Process Kaigo',
        "title_ja": '介護過程',
        "description": 'Panduan lengkap 介護過程 dalam kaigo: teori, prosedur, dialog Jepang, kosakata, dan quiz persiapan ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 3,
        "duration": 10,
        "prerequisite": 'Kaigo-Rekod',
        "tags": ['dokumentasi', 'rekod', 'ujian'],
        "recommended_next": 'Kaigo-Rekod-Lanjut',
        "icon": '🔄',
    },
    'Kaigo-Rekod-Lanjut': {
        "filename": 'Kaigo-Rekod-Lanjut.html',
        "category": 'dokumen',
        "title": 'Rekod & Dokumentasi Kaigo Lanjutan 介護記録',
        "title_ja": '介護記録',
        "description": 'Panduan lengkap penulisan rekod kaigo — SOAPノート, observasi objektif vs subjektif, terminologi rekod, dan contoh dokumentasi.',
        "level": 'mahir',
        "order": 4,
        "duration": 10,
        "prerequisite": 'Kaigo-Kaigo-Katei',
        "tags": ['dokumentasi', 'rekod'],
        "recommended_next": None,
        "icon": '🗄️',
    },

    # ── hukum ──
    'Kaigo-Jinken-Fukushi': {
        "filename": 'Kaigo-Jinken-Fukushi.html',
        "category": 'hukum',
        "title": 'Hak Asasi Manusia & Kesejahteraan',
        "title_ja": '人権と福祉',
        "description": 'Panduan profesional 人権と福祉 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'pemula',
        "order": 1,
        "duration": 10,
        "prerequisite": None,
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Kaigo-Rinri',
        "icon": '✊',
    },
    'Kaigo-Kaigo-Rinri': {
        "filename": 'Kaigo-Kaigo-Rinri.html',
        "category": 'hukum',
        "title": 'Etika Perawatan Profesional',
        "title_ja": '介護の倫理',
        "description": 'Panduan profesional 介護の倫理 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'pemula',
        "order": 2,
        "duration": 10,
        "prerequisite": None,
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Hukum',
        "icon": '🧭',
    },
    'Kaigo-Hukum': {
        "filename": 'Kaigo-Hukum.html',
        "category": 'hukum',
        "title": '介護福祉士',
        "title_ja": None,
        "description": 'Hukum, sistem, dan etika perawatan 介護福祉士: regulasi kaigo Jepang, hak lansia, UU kesehatan, dan standar etika profesional.',
        "level": 'menengah',
        "order": 3,
        "duration": 11,
        "prerequisite": 'Kaigo-Kaigo-Rinri',
        "tags": ['hukum', 'etika', 'lansia'],
        "recommended_next": 'Kaigo-Kaigo-Hoken-Detail',
        "icon": '⚖️',
    },
    'Kaigo-Kaigo-Hoken-Detail': {
        "filename": 'Kaigo-Kaigo-Hoken-Detail.html',
        "category": 'hukum',
        "title": 'Detail Sistem Asuransi Perawatan',
        "title_ja": '介護保険制度の詳細',
        "description": 'Panduan profesional 介護保険制度の詳細 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'mahir',
        "order": 4,
        "duration": 10,
        "prerequisite": 'Kaigo-Hukum',
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Shakai-Hosho',
        "icon": '🏦',
    },
    'Kaigo-Shakai-Hosho': {
        "filename": 'Kaigo-Shakai-Hosho.html',
        "category": 'hukum',
        "title": 'Sistem Jaminan Sosial Jepang',
        "title_ja": '社会保障制度',
        "description": 'Panduan lengkap社会保障制度 Jepang dalam kaigo: 介護保険, 年金, 医療保険, 障害者福祉, tingkat kebutuhan perawatan (要介護認定), kosakata, dan quiz ujian Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 5,
        "duration": 10,
        "prerequisite": 'Kaigo-Kaigo-Hoken-Detail',
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Shogaisha-Shien',
        "icon": '🛡️',
    },
    'Kaigo-Shogaisha-Shien': {
        "filename": 'Kaigo-Shogaisha-Shien.html',
        "category": 'hukum',
        "title": 'Sistem Dukungan Penyandang Disabilitas',
        "title_ja": '障害者支援制度',
        "description": 'Panduan profesional 障害者支援制度 dalam kaigo: teori mendalam, prosedur, tabel perbandingan, dialog situasional, kosakata TTS, dan quiz ujian nasional Kaigo Fukushishi.',
        "level": 'menengah',
        "order": 6,
        "duration": 10,
        "prerequisite": 'Kaigo-Shakai-Hosho',
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Gyakutai-Boshi',
        "icon": '♿',
    },
    'Kaigo-Gyakutai-Boshi': {
        "filename": 'Kaigo-Gyakutai-Boshi.html',
        "category": 'hukum',
        "title": 'Pencegahan Kekerasan pada Lansia',
        "title_ja": '虐待防止',
        "description": 'Panduan lengkap 虐待防止 dalam kaigo untuk ujian介護福祉士: teori, prosedur, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'menengah',
        "order": 7,
        "duration": 10,
        "prerequisite": 'Kaigo-Shogaisha-Shien',
        "tags": ['hukum', 'etika', 'lansia', 'ujian'],
        "recommended_next": 'Kaigo-Kojin-Joho',
        "icon": '🚫',
    },
    'Kaigo-Kojin-Joho': {
        "filename": 'Kaigo-Kojin-Joho.html',
        "category": 'hukum',
        "title": 'Perlindungan Data Pribadi dalam Kaigo',
        "title_ja": '個人情報保護',
        "description": 'Panduan lengkap 個人情報保護 dalam kaigo untuk ujian介護福祉士: teori, contoh, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'menengah',
        "order": 8,
        "duration": 10,
        "prerequisite": 'Kaigo-Gyakutai-Boshi',
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Risk-Management',
        "icon": '🔒',
    },
    'Kaigo-Risk-Management': {
        "filename": 'Kaigo-Risk-Management.html',
        "category": 'hukum',
        "title": 'Manajemen Risiko dalam Kaigo',
        "title_ja": 'リスクマネジメント',
        "description": 'Panduan lengkap リスクマネジメント dalam kaigo untuk ujian介護福祉士: teori, prosedur, dialog bahasa Jepang, kosakata, dan quiz persiapan ujian nasional.',
        "level": 'menengah',
        "order": 9,
        "duration": 10,
        "prerequisite": 'Kaigo-Kojin-Joho',
        "tags": ['hukum', 'etika', 'ujian'],
        "recommended_next": 'Kaigo-Hukum-Lanjut',
        "icon": '⚠️',
    },
    'Kaigo-Hukum-Lanjut': {
        "filename": 'Kaigo-Hukum-Lanjut.html',
        "category": 'hukum',
        "title": 'Hukum & Regulasi Kaigo 介護法規',
        "title_ja": '介護法規',
        "description": 'Hukum & Regulasi Kaigo 介護法規 — Nihonggo Pro Academy',
        "level": 'mahir',
        "order": 10,
        "duration": 10,
        "prerequisite": 'Kaigo-Risk-Management',
        "tags": ['hukum', 'etika'],
        "recommended_next": None,
        "icon": '📜',
    },

    # ── ujian ──
    'Kaigo-Ujian-N2': {
        "filename": 'Kaigo-Ujian-N2.html',
        "category": 'ujian',
        "title": 'Quiz Kaigo Level N2 介護N2',
        "title_ja": None,
        "description": 'Latihan soal ujian kaigo level N2 介護N2. Simulasi soal bahasa Jepang untuk tenaga kaigo bersertifikat di fasilitas perawatan Jepang.',
        "level": 'mahir',
        "order": 1,
        "duration": 10,
        "prerequisite": None,
        "tags": ['ujian', 'latihan', 'n2'],
        "recommended_next": 'Kaigo-Ujian-Nasional',
        "icon": '📊',
    },
    'Kaigo-Ujian-Nasional': {
        "filename": 'Kaigo-Ujian-Nasional.html',
        "category": 'ujian',
        "title": '介護福祉士',
        "title_ja": '国家試験',
        "description": 'Latihan soal ujian nasional 国家試験 介護福祉士: bank soal pilihan ganda, materi prioritas, dan strategi lulus ujian kaigo Jepang.',
        "level": 'mahir',
        "order": 2,
        "duration": 56,
        "prerequisite": 'Kaigo-Ujian-N2',
        "tags": ['ujian', 'latihan'],
        "recommended_next": 'Kaigo-Ujian-Kokoro-Karada',
        "icon": '🎓',
    },
    'Kaigo-Ujian-Kokoro-Karada': {
        "filename": 'Kaigo-Ujian-Kokoro-Karada.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — こころとからだのしくみ',
        "title_ja": 'こころとからだのしくみ',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang こころとからだのしくみ (Struktur Jiwa & Tubuh): psikologi, sistem tubuh, penyakit lansia, penuaan. 20 soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 3,
        "duration": 30,
        "prerequisite": 'Kaigo-Ujian-Nasional',
        "tags": ['ujian', 'latihan', 'kokoro-karada', 'psikologi', 'tubuh'],
        "recommended_next": 'Kaigo-Ujian-Ninchisho',
        "icon": '🧠',
    },
    'Kaigo-Ujian-Ninchisho': {
        "filename": 'Kaigo-Ujian-Ninchisho.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 認知症の理解',
        "title_ja": '認知症の理解',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 認知症の理解 (Pemahaman Demensia): jenis demensia, gejala inti & BPSD, perawatan berpusat pada orang, dukungan keluarga. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 4,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Kokoro-Karada',
        "tags": ['ujian', 'latihan', 'demensia', 'ninchisho', 'bpsd'],
        "recommended_next": 'Kaigo-Ujian-Iryo-Care',
        "icon": '🧩',
    },
    'Kaigo-Ujian-Iryo-Care': {
        "filename": 'Kaigo-Ujian-Iryo-Care.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 医療的ケア',
        "title_ja": '医療的ケア',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 医療的ケア (Perawatan Medis): penyedotan dahak, nutrisi enteral, tanda vital, pencegahan infeksi. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 5,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Ninchisho',
        "tags": ['ujian', 'latihan', 'medis', 'iryo', 'kyuin'],
        "recommended_next": 'Kaigo-Ujian-Shakai',
        "icon": '🩺',
    },
    'Kaigo-Ujian-Shakai': {
        "filename": 'Kaigo-Ujian-Shakai.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 社会の理解',
        "title_ja": '社会の理解',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 社会の理解 (Pemahaman Sosial): sistem asuransi perawatan, dukungan disabilitas, jaminan sosial Jepang. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 6,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Iryo-Care',
        "tags": ['ujian', 'latihan', 'sosial', 'shakai', 'asuransi'],
        "recommended_next": 'Kaigo-Ujian-Kihon',
        "icon": '🏛️',
    },
    'Kaigo-Ujian-Kihon': {
        "filename": 'Kaigo-Ujian-Kihon.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 介護の基本',
        "title_ja": '介護の基本',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 介護の基本 (Dasar Perawatan): martabat, kemandirian, ICF, manajemen risiko, kerja tim, etika profesi. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 7,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Shakai',
        "tags": ['ujian', 'latihan', 'dasar', 'kihon', 'etika'],
        "recommended_next": 'Kaigo-Ujian-Seikatsu-Shien',
        "icon": '📋',
    },
    'Kaigo-Ujian-Seikatsu-Shien': {
        "filename": 'Kaigo-Ujian-Seikatsu-Shien.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 生活支援技術',
        "title_ja": '生活支援技術',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 生活支援技術 (Teknik Dukungan Hidup): bantuan makan, mandi, ekskresi, berpakaian, transfer, mekanika tubuh. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 8,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Kihon',
        "tags": ['ujian', 'latihan', 'teknik', 'seikatsu', 'ijou'],
        "recommended_next": 'Kaigo-Ujian-Hattatsu-Roka',
        "icon": '🛁',
    },
    'Kaigo-Ujian-Hattatsu-Roka': {
        "filename": 'Kaigo-Ujian-Hattatsu-Roka.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 発達と老化の理解',
        "title_ja": '発達と老化の理解',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 発達と老化の理解 (Perkembangan & Penuaan): tahap perkembangan Erikson, penuaan fisiologis, sarkopenia, sindrom geriatri. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 9,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Seikatsu-Shien',
        "tags": ['ujian', 'latihan', 'penuaan', 'hattatsu', 'roka'],
        "recommended_next": 'Kaigo-Ujian-Shogai',
        "icon": '🌱',
    },
    'Kaigo-Ujian-Shogai': {
        "filename": 'Kaigo-Ujian-Shogai.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 障害の理解',
        "title_ja": '障害の理解',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 障害の理解 (Pemahaman Disabilitas): disabilitas fisik/intelektual/psikis, akomodasi wajar, penerimaan disabilitas, desain universal. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 10,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Hattatsu-Roka',
        "tags": ['ujian', 'latihan', 'disabilitas', 'shogai', 'barrier-free'],
        "recommended_next": 'Kaigo-Ujian-Songen',
        "icon": '♿',
    },
    'Kaigo-Ujian-Songen': {
        "filename": 'Kaigo-Ujian-Songen.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 人間の尊厳と自立',
        "title_ja": '人間の尊厳と自立',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 人間の尊厳と自立 (Martabat & Kemandirian): hak asasi, penentuan diri, advokasi, pencegahan penelantaran, informed consent. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 11,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Shogai',
        "tags": ['ujian', 'latihan', 'martabat', 'songen', 'hak'],
        "recommended_next": 'Kaigo-Ujian-Ningen-Kankei',
        "icon": '🕊️',
    },
    'Kaigo-Ujian-Ningen-Kankei': {
        "filename": 'Kaigo-Ujian-Ningen-Kankei.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 人間関係とコミュニケーション',
        "title_ja": '人間関係とコミュニケーション',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 人間関係とコミュニケーション (Hubungan & Komunikasi): rapport, empati, mendengar aktif, kesadaran diri, prinsip Biestek. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 12,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Songen',
        "tags": ['ujian', 'latihan', 'komunikasi', 'empati', 'rapport'],
        "recommended_next": 'Kaigo-Ujian-Comm-Gijutsu',
        "icon": '🤝',
    },
    'Kaigo-Ujian-Comm-Gijutsu': {
        "filename": 'Kaigo-Ujian-Comm-Gijutsu.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — コミュニケーション技術',
        "title_ja": 'コミュニケーション技術',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang コミュニケーション技術 (Teknik Komunikasi): komunikasi dengan afasia, gangguan sensorik, demensia, rekaman & pelaporan. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 13,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Ningen-Kankei',
        "tags": ['ujian', 'latihan', 'komunikasi', 'teknik', 'afasia'],
        "recommended_next": 'Kaigo-Ujian-Kaigo-Katei',
        "icon": '💬',
    },
    'Kaigo-Ujian-Kaigo-Katei': {
        "filename": 'Kaigo-Ujian-Kaigo-Katei.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 介護過程',
        "title_ja": '介護過程',
        "description": 'Simulasi ujian nasional 介護福祉士 bidang 介護過程 (Proses Perawatan): asesmen, perencanaan, implementasi, evaluasi, ICF, siklus PDCA. Soal dengan pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 14,
        "duration": 25,
        "prerequisite": 'Kaigo-Ujian-Comm-Gijutsu',
        "tags": ['ujian', 'latihan', 'proses', 'katei', 'asesmen'],
        "recommended_next": 'Kaigo-Ujian-Sogo-Mondai',
        "icon": '🔄',
    },
    'Kaigo-Ujian-Sogo-Mondai': {
        "filename": 'Kaigo-Ujian-Sogo-Mondai.html',
        "category": 'ujian',
        "title": 'Simulasi Ujian — 総合問題 (Soal Kasus)',
        "title_ja": '総合問題',
        "description": 'Latihan 総合問題 ujian nasional 介護福祉士: 30 soal berbasis kasus (10 事例) yang mengintegrasikan komunikasi, teknik perawatan, etika, dan proses perawatan dalam skenario利用者 nyata. Pembahasan dwibahasa.',
        "level": 'mahir',
        "order": 15,
        "duration": 45,
        "prerequisite": 'Kaigo-Ujian-Kaigo-Katei',
        "tags": ['ujian', 'latihan', 'kasus', 'sogo', 'jirei', 'terintegrasi'],
        "recommended_next": None,
        "icon": '📚',
    },
    'Kaigo-Mensetsu-Taisaku': {
        "filename": 'Kaigo-Mensetsu-Taisaku.html',
        "category": 'bahasa',
        "title": 'Persiapan Wawancara Kaigo 面接対策',
        "title_ja": '面接対策',
        "description": 'Persiapan wawancara kerja kaigo 面接対策 untuk kandidat EPA & Tokutei Ginou: pertanyaan umum, jawaban model, perkenalan diri, keigo, dan etika wawancara Jepang. Latihan dengan pembahasan dwibahasa.',
        "level": 'menengah',
        "order": 15,
        "duration": 30,
        "prerequisite": None,
        "tags": ['bahasa', 'komunikasi', 'wawancara', 'mensetsu', 'epa', 'ssw', 'keigo'],
        "recommended_next": None,
        "icon": '🤝',
    },
    'Kaigo-Kurumaisu': {
        "filename": 'Kaigo-Kurumaisu.html',
        "category": 'praktik',
        "title": 'Teknik Kursi Roda 車椅子介助',
        "title_ja": '車椅子介助',
        "description": 'Modul teknik kursi roda 車椅子介助: bagian kursi roda, cara mendorong aman, naik-turun, rem, dan transfer. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 17,
        "duration": 25,
        "prerequisite": None,
        "tags": ['praktik', 'kursi-roda', 'kurumaisu', 'mobilitas'],
        "recommended_next": None,
        "icon": '♿',
    },
    'Kaigo-Hoko-Kaijo': {
        "filename": 'Kaigo-Hoko-Kaijo.html',
        "category": 'praktik',
        "title": 'Bantuan Berjalan 歩行介助',
        "title_ja": '歩行介助',
        "description": 'Modul bantuan berjalan 歩行介助: posisi pendamping, alat bantu jalan, pencegahan jatuh, dan teknik untuk hemiplegia. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 18,
        "duration": 25,
        "prerequisite": None,
        "tags": ['praktik', 'jalan', 'hoko', 'jatuh'],
        "recommended_next": None,
        "icon": '🚶',
    },
    'Kaigo-Vital-Sign': {
        "filename": 'Kaigo-Vital-Sign.html',
        "category": 'kesehatan',
        "title": 'Tanda Vital バイタルサイン',
        "title_ja": 'バイタルサイン',
        "description": 'Modul tanda vital バイタルサイン: suhu, nadi, tekanan darah, pernapasan, SpO2, nilai normal, dan kapan melapor. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 22,
        "duration": 25,
        "prerequisite": None,
        "tags": ['kesehatan', 'vital', 'baital', 'observasi'],
        "recommended_next": None,
        "icon": '🌡️',
    },
    'Kaigo-Fukuyaku': {
        "filename": 'Kaigo-Fukuyaku.html',
        "category": 'kesehatan',
        "title": 'Dukungan Obat 服薬支援',
        "title_ja": '服薬支援',
        "description": 'Modul dukungan obat 服薬支援: aturan pemberian obat, batas kewenangan介護職, cek 5 benar, efek samping, dan pelaporan. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 23,
        "duration": 25,
        "prerequisite": None,
        "tags": ['kesehatan', 'obat', 'fukuyaku', 'medikasi'],
        "recommended_next": None,
        "icon": '💊',
    },
    'Kaigo-CPR': {
        "filename": 'Kaigo-CPR.html',
        "category": 'kesehatan',
        "title": 'Dasar CPR 心肺蘇生',
        "title_ja": '心肺蘇生法',
        "description": 'Modul dasar CPR 心肺蘇生法: cek kesadaran, panggil bantuan, kompresi dada, AED, dan alur救命. Untuk situasi darurat kaigo. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 24,
        "duration": 25,
        "prerequisite": None,
        "tags": ['kesehatan', 'cpr', 'darurat', 'kyumei'],
        "recommended_next": None,
        "icon": '🫀',
    },
    'Kaigo-Kasai-Hinan': {
        "filename": 'Kaigo-Kasai-Hinan.html',
        "category": 'praktik',
        "title": 'Evakuasi Kebakaran 火災避難',
        "title_ja": '火災・避難',
        "description": 'Modul evakuasi kebakaran 火災避難: alur saat kebakaran, prioritas evakuasi lansia, alat pemadam, dan pencegahan. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 19,
        "duration": 25,
        "prerequisite": None,
        "tags": ['praktik', 'kebakaran', 'kasai', 'keselamatan', 'evakuasi'],
        "recommended_next": None,
        "icon": '🔥',
    },
    'Kaigo-Jishin-Saigai': {
        "filename": 'Kaigo-Jishin-Saigai.html',
        "category": 'praktik',
        "title": 'Respons Gempa & Bencana 地震・災害対応',
        "title_ja": '地震・災害対応',
        "description": 'Modul respons gempa & bencana 地震・災害対応: tindakan saat gempa, evakuasi lansia, persiapan darurat, dan BCP. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 20,
        "duration": 25,
        "prerequisite": None,
        "tags": ['praktik', 'gempa', 'jishin', 'bencana', 'saigai'],
        "recommended_next": None,
        "icon": '🌊',
    },
    'Kaigo-Shuhi-Gimu': {
        "filename": 'Kaigo-Shuhi-Gimu.html',
        "category": 'hukum',
        "title": 'Kerahasiaan 守秘義務',
        "title_ja": '守秘義務',
        "description": 'Modul kerahasiaan 守秘義務: kewajiban menjaga rahasia, perlindungan data pribadi, media sosial, dan etika informasi. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 11,
        "duration": 25,
        "prerequisite": None,
        "tags": ['hukum', 'kerahasiaan', 'shuhi', 'privasi', 'etika'],
        "recommended_next": None,
        "icon": '🔐',
    },
    'Kaigo-Shokuba-Bunka': {
        "filename": 'Kaigo-Shokuba-Bunka.html',
        "category": 'bahasa',
        "title": 'Budaya Kerja Jepang 職場文化',
        "title_ja": '職場文化',
        "description": 'Modul budaya kerja Jepang 職場文化: 報連相, ketepatan waktu, kerja tim, hierarki, dan adaptasi pekerja asing. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 16,
        "duration": 30,
        "prerequisite": None,
        "tags": ['bahasa', 'budaya', 'shokuba', 'kerja', 'houkoku'],
        "recommended_next": None,
        "icon": '🏢',
    },
    'Kaigo-Setsugu': {
        "filename": 'Kaigo-Setsugu.html',
        "category": 'bahasa',
        "title": 'Pelayanan (接遇) 接遇マナー',
        "title_ja": '接遇マナー',
        "description": 'Modul pelayanan 接遇マナー: sikap ramah, keigo dasar, senyum, dan menghormati利用者 sebagai pelanggan. Latihan dwibahasa.',
        "level": 'menengah',
        "order": 18,
        "duration": 25,
        "prerequisite": None,
        "tags": ['bahasa', 'setsugu', 'pelayanan', 'keigo', 'manner'],
        "recommended_next": None,
        "icon": '🙇',
    },
}


# ── Helper ──────────────────────────────────────────────────────────────────
CATEGORY_NAMES = {k: n for k, n, _, _ in CATEGORIES}
CATEGORY_ICONS = {k: i for k, _, i, _ in CATEGORIES}
LEVEL_NAMES = {k: n for k, n, _ in LEVELS}
LEVEL_ORDER = {k: o for k, _, o in LEVELS}


def modules_in(category):
    """Modul satu kategori, terurut sesuai kurikulum."""
    return sorted(
        ((s, m) for s, m in MODULES.items() if m['category'] == category),
        key=lambda x: x[1]['order'],
    )


def learning_path(category):
    """Rute belajar: daftar slug berurutan untuk satu kategori."""
    return [s for s, _ in modules_in(category)]


def total_duration(category=None):
    """Total menit; seluruh katalog bila category None."""
    items = MODULES.values() if category is None else (
        m for m in MODULES.values() if m['category'] == category
    )
    return sum(m['duration'] for m in items)
